name: Publish dev docs

on:
  push:
    # Only build dev docs based on the branch for the latest release...
    branches:
      - v0.9

jobs:
  publish_dev_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Update mirrors
        working-directory: /home/runner/work/Moorhen/
        run: sudo apt-get update -y

      - name: Install dependencies 
        working-directory: /home/runner/work/Moorhen/
        run: |    
          sudo apt-get install -y npm

      - name: Create mock version file
        working-directory: /home/runner/work/Moorhen/       
        run: |    
          echo "export const version = 0.1" > /home/runner/work/Moorhen/Moorhen/baby-gru/src/version.js

      - name: npm install
        working-directory: /home/runner/work/Moorhen/Moorhen/baby-gru
        run: npm install

      - name: compile jsDocs
        working-directory: /home/runner/work/Moorhen/Moorhen/baby-gru
        run: |
          npm install --force better-docs
          npx jsdoc -c jsdoc.json    
          
      - name: Publishing on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /home/runner/work/Moorhen/Moorhen/baby-gru/docs
