name: Test tsc compilation

on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: yarn install
      working-directory: /home/runner/work/Moorhen/Moorhen/baby-gru
      run: yarn install
    - name: tsc compile
      uses: iCrawl/action-tsc@v1
      with:
        project: baby-gru/tsconfig.json