name: Test tsc compilation

on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node.js v16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: npm install
      working-directory: /home/runner/work/Moorhen/Moorhen/baby-gru
      run: npm install
    - name: tsc compile
      uses: iCrawl/action-tsc@v1
      with:
        project: /home/runner/work/Moorhen/Moorhen/baby-gru/