name: Test tsc compilation

on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install node.js v16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies 
      working-directory: /home/runner/work/Moorhen/       
      run: |    
        sudo apt-get install -y npm         
    - name: yarn install
      working-directory: /home/runner/work/Moorhen/Moorhen/baby-gru
      run: yarn install
    - name: tsc compile
      working-directory: /home/runner/work/Moorhen/Moorhen/baby-gru
      run: |             
        cd /home/runner/work/Moorhen/Moorhen/baby-gru/
        npx tsc /home/runner/work/Moorhen/Moorhen/baby-gru/tsconfig.json
